[
    {
        "o+":{
            maharashtra:{
                abad:[accId,accId,accId],
                pune:[accId,accId,accId]
            },
            gujrat:{
                ahemdabad:[accId,accId,accId]
            }
        },
        "o-":{
            maharashtra:{
                abad:[accId,accId,accId],
                pune:[accId,accId,accId]
            },
            gujrat:{
                ahemdabad:[accId,accId,accId]
            }
        },
    }
]